package shell

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// DefaultConfigs defines the default tool config files generated by --init-config.
// Also used as embedded fallback by the engine when no disk configs exist.
var DefaultConfigs = map[string]string{
	"text-processing.toml": `[awk]
allowed = ["*"]
[column]
allowed = ["*"]
[cat]
allowed = ["*"]
[cut]
allowed = ["*"]
[diff]
allowed = ["*"]
[grep]
allowed = ["*"]
[head]
allowed = ["*"]
[jq]
allowed = ["*"]
[paste]
allowed = ["*"]
[rg]
allowed = ["*"]
[sed]
allowed = ["*"]
write_flags = ["-i", "--in-place"]
write_target = "last"
flags_with_value = ["-e", "-f", "--expression", "--file"]
[sort]
allowed = ["*"]
[tail]
allowed = ["*"]
[tr]
allowed = ["*"]
[uniq]
allowed = ["*"]
[wc]
allowed = ["*"]
[tac]
allowed = ["*"]
[yq]
allowed = ["*"]
write_flags = ["-i", "--inplace"]
write_target = "last"
flags_with_value = ["-P", "--output-format", "-I", "--indent", "-o"]
`,

	"filesystem.toml": `[basename]
allowed = ["*"]
[dirname]
allowed = ["*"]
[du]
allowed = ["*"]
[file]
allowed = ["*"]
[find]
allowed = ["*"]
[ls]
allowed = ["*"]
[readlink]
allowed = ["*"]
[realpath]
allowed = ["*"]
[stat]
allowed = ["*"]
[tree]
allowed = ["*"]
`,

	"filesystem-write.toml": `[cp]
allowed = ["*"]
write_target = "last"
flags_with_value = ["-t", "--target-directory"]
[ln]
allowed = ["*"]
write_target = "last"
flags_with_value = ["-t", "--target-directory", "-S", "--suffix"]
[mkdir]
allowed = ["*"]
write_target = "all"
[mv]
allowed = ["*"]
write_target = "last"
flags_with_value = ["-t", "--target-directory"]
[tee]
allowed = ["*"]
write_target = "all"
[touch]
allowed = ["*"]
write_target = "all"
[chmod]
allowed = ["*"]
write_target = "last"
`,

	"network.toml": `[curl]
allowed = ["*"]
[dig]
allowed = ["*"]
[host]
allowed = ["*"]
[nslookup]
allowed = ["*"]
[ping]
allowed = ["*"]
[ss]
allowed = ["*"]
[nc]
allowed = ["*"]
[netcat]
allowed = ["*"]
[traceroute]
allowed = ["*"]
[wget]
allowed = ["*"]
[whois]
allowed = ["*"]
`,

	"system-info.toml": `[date]
allowed = ["*"]
[df]
allowed = ["*"]
[dmesg]
allowed = ["*"]
[free]
allowed = ["*"]
[getconf]
allowed = ["*"]
[groups]
allowed = ["*"]
[hostname]
allowed = ["*"]
[id]
allowed = ["*"]
[locale]
allowed = ["*"]
[lsof]
allowed = ["*"]
[lsblk]
allowed = ["*"]
[lscpu]
allowed = ["*"]
[lsmem]
allowed = ["*"]
[lsmod]
allowed = ["*"]
[lspci]
allowed = ["*"]
[lsusb]
allowed = ["*"]
[nproc]
allowed = ["*"]
[pgrep]
allowed = ["*"]
[printenv]
allowed = ["*"]
[ps]
allowed = ["*"]
[timedatectl]
allowed = ["*"]
[uname]
allowed = ["*"]
[uptime]
allowed = ["*"]
[whoami]
allowed = ["*"]
`,

	"utilities.toml": `[base64]
allowed = ["*"]
[bc]
allowed = ["*"]
[echo]
allowed = ["*"]
[env]
allowed = ["*"]
[envsubst]
allowed = ["*"]
[mktemp]
allowed = ["*"]
[md5sum]
allowed = ["*"]
[sha1sum]
allowed = ["*"]
[sha256sum]
allowed = ["*"]
[seq]
allowed = ["*"]
[sleep]
allowed = ["*"]
[type]
allowed = ["*"]
[whereis]
allowed = ["*"]
[which]
allowed = ["*"]
[printf]
allowed = ["*"]
[test]
allowed = ["*"]
`,

	"kubernetes.toml": `[kubectl-readonly]
allowed = ["*"]

[kubectx]
allowed = ["*"]

[krew]
allowed = ["list", "search", "info", "version"]

[kubectl-crossplane]
allowed = ["version", "trace"]

[kustomize]
allowed = ["version", "build", "cfg"]
[kustomize.subcommands]
cfg = ["tree", "cat", "grep"]

[docker-compose]
allowed = ["version", "config", "convert", "ps", "logs", "images", "top", "port", "events", "ls"]
flags_with_value = ["-f", "--file", "-p", "--project-name", "--profile", "--project-directory", "--env-file", "--ansi"]

[helm]
allowed = ["version", "env", "list", "status", "history", "template", "lint", "verify", "get", "show", "search", "repo"]
flags_with_value = ["-n", "--namespace", "--kube-context", "--kubeconfig", "--kube-apiserver", "--kube-as-user", "--kube-as-group", "--kube-ca-file", "--kube-token", "--registry-config", "--repository-cache", "--repository-config"]
[helm.subcommands]
get = ["values", "manifest", "all", "notes", "hooks"]
show = ["chart", "values", "readme", "all", "crds"]
search = ["repo", "hub"]
repo = ["list"]

[stern]
allowed = ["*"]

[flux]
allowed = ["version", "tree", "trace", "events", "logs", "get"]
flags_with_value = ["-n", "--namespace", "--context", "--kubeconfig", "-s", "--server", "--as", "--as-group", "--as-uid", "--cluster", "--cache-dir", "--certificate-authority", "--client-certificate", "--client-key", "--tls-server-name", "--token"]
[flux.subcommands]
get = ["all", "kustomizations", "helmreleases", "helmcharts", "helmrepositories", "gitrepositories", "buckets", "ocirepositories", "sources", "alerts", "providers", "receivers", "images", "imagepolicies", "imagerepositories", "imageupdateautomations", "events"]
`,

	"dev-tools.toml": `[make]
allowed = ["*"]

[shellcheck]
allowed = ["*"]

[yamllint]
allowed = ["*"]
`,

	"typescript.toml": `[tsc]
allowed = ["*"]

[npx]
allowed = ["tsc", "eslint", "prettier", "jest", "vitest", "tsx"]

[eslint]
allowed = ["*"]
write_flags = ["--fix"]
write_target = "all"
flags_with_value = ["-c", "--config", "--ext", "--output-file", "--resolve-plugins-relative-to", "--rulesdir", "--plugin", "--rule", "--parser-options", "--format", "-f", "-o", "--ignore-path"]

[prettier]
allowed = ["*"]
write_flags = ["--write", "-w"]
write_target = "all"
flags_with_value = ["--config", "--ignore-path", "--plugin", "--parser", "--tab-width", "--print-width", "--trailing-comma", "--end-of-line", "--arrow-parens", "--prose-wrap", "--log-level", "--range-start", "--range-end"]
`,

	"go.toml": `[gofmt]
allowed = ["*"]
write_flags = ["-w"]
write_target = "all"

[go]
allowed = ["test", "build", "vet", "fmt", "mod", "generate", "doc", "version", "env", "list", "tool"]

[goreleaser]
allowed = ["check", "build"]
`,

	"rust.toml": `[cargo]
allowed = ["build", "check", "test", "clippy", "fmt", "doc", "bench", "clean", "update", "metadata", "tree", "version"]

[rustc]
allowed = ["*"]
`,

	"python.toml": `[ruff]
allowed = ["*"]
write_flags = ["--fix", "--fix-only"]
write_target = "last"
flags_with_value = ["--config", "--select", "--ignore", "--extend-select", "--extend-ignore", "--target-version", "--line-length", "--output-format", "-o"]

[ty]
allowed = ["*"]

[uv]
allowed = ["run", "sync", "lock", "venv", "version", "python", "pip"]
flags_with_value = ["--group", "--extra", "--python", "--directory", "--project"]
[uv.subcommands]
run = ["pytest", "mypy", "pyright", "ty", "ruff", "black", "isort", "pylint", "flake8", "bandit", "pip-audit"]
python = ["list", "find", "pin"]
pip = ["list", "show", "check", "tree", "compile"]
`,

	"system-restricted.toml": `[journalctl]
allowed = ["*"]

[systemctl]
allowed = ["is-active", "is-enabled", "list-units", "status"]

[ip]
allowed = ["addr", "link", "route"]

[gsettings]
allowed = ["get"]

[gnome-extensions]
allowed = ["list", "show"]

[udevadm]
allowed = ["info"]

[xdg-mime]
allowed = ["query"]

[flatpak]
allowed = ["list"]

[apt]
allowed = ["list"]
`,

	"concourse.toml": `[fly]
allowed = ["builds", "bs", "containers", "cs", "completion", "format-pipeline", "fp", "get-pipeline", "gp", "jobs", "js", "pipelines", "ps", "resource-versions", "rvs", "resources", "rs", "status", "targets", "ts", "teams", "userinfo", "validate-pipeline", "vp", "version", "volumes", "vs", "watch", "w", "workers", "ws"]
flags_with_value = ["-t", "--target", "-p", "--pipeline", "-j", "--job", "-b", "--build", "-n", "--team-name", "-c", "--config"]
`,

	"sops.toml": `[sops]
allowed = ["filestatus", "encrypt"]
flags_with_value = ["--output", "--input-type", "--output-type", "--filename-override", "--config", "--kms", "--gcp-kms", "--azure-kv", "--hc-vault-transit", "--age", "--pgp", "--unencrypted-suffix", "--encrypted-suffix", "--unencrypted-regex", "--encrypted-regex", "--encryption-context"]
write_flags = ["-i", "--in-place"]
write_target = "last"
`,

	"terraform.toml": `[terraform]
allowed = ["fmt", "get", "graph", "init", "output", "plan", "providers", "show", "state", "validate", "version", "workspace"]
flags_with_value = ["-chdir", "-var", "-var-file", "-target", "-out", "-state", "-backup", "-lock-timeout", "-parallelism", "-plugin-dir"]
[terraform.env]
TF_INPUT = "false"
TF_IN_AUTOMATION = "true"
[terraform.subcommands]
providers = ["schema"]
state = ["list", "show", "pull"]
workspace = ["list", "show"]
`,

	"gsutil.toml": `[gsutil]
allowed = ["ls", "cat", "stat", "du", "hash", "version", "help", "acl", "cors", "defacl", "iam", "label", "lifecycle", "logging", "notification", "pap", "requesterpays", "retention", "versioning", "web"]
[gsutil.subcommands]
acl = ["get"]
cors = ["get"]
defacl = ["get"]
iam = ["get"]
label = ["get"]
lifecycle = ["get"]
logging = ["get"]
notification = ["list"]
pap = ["get"]
requesterpays = ["get"]
retention = ["get"]
versioning = ["get"]
web = ["get"]
`,
}

// auditConfigBlock returns the [audit] TOML block with a XDG-based default path.
func auditConfigBlock() string {
	dataHome := os.Getenv("XDG_DATA_HOME")
	if dataHome == "" {
		home, _ := os.UserHomeDir()
		dataHome = filepath.Join(home, ".local", "share")
	}
	auditFile := filepath.Join(dataHome, "agent-callable", "audit.log")
	return fmt.Sprintf(`
[audit]
file = %q
mode = "none"  # "none" (disabled), "blocked", "allowed", "all"
max_entries = 10000  # 0 = unlimited
mask_secrets = true
# include_audit_checks = false
`, auditFile)
}

// ConfigCategory groups related config files under a user-facing label.
type ConfigCategory struct {
	Label    string   // display name (e.g. "Kubernetes")
	Desc     string   // short description of what's included
	Files    []string // TOML file names from DefaultConfigs
	Builtins []string // built-in tool names gated by this category
}

// Categories defines the interactive selection groups for --init-config.
// Order matters: displayed in this sequence.
var Categories = []ConfigCategory{
	{
		Label:    "Git & GitHub",
		Desc:     "git, gh (GitHub CLI)",
		Builtins: []string{"git", "gh"},
	},
	{
		Label: "Text processing",
		Desc:  "awk, cat, cut, diff, grep, head, jq, sed, sort, tail, tr, wc, yq...",
		Files: []string{"text-processing.toml"},
	},
	{
		Label: "Filesystem (read-only)",
		Desc:  "ls, find, file, stat, tree, readlink, du...",
		Files: []string{"filesystem.toml"},
	},
	{
		Label: "Filesystem (write)",
		Desc:  "cp, ln, mkdir, mv, tee, touch, chmod (writable_dirs enforced)",
		Files: []string{"filesystem-write.toml"},
	},
	{
		Label: "System info",
		Desc:  "ps, free, df, uname, hostname, lscpu, lsblk, uptime...",
		Files: []string{"system-info.toml"},
	},
	{
		Label: "System services",
		Desc:  "systemctl (read-only), journalctl, ip, apt list, flatpak list...",
		Files: []string{"system-restricted.toml"},
	},
	{
		Label:    "Utilities",
		Desc:     "echo, env, base64, printf, md5sum, sleep, timeout, nice, xargs, which, type...",
		Files:    []string{"utilities.toml"},
		Builtins: []string{"timeout", "nice", "xargs"},
	},
	{
		Label: "Network",
		Desc:  "curl, dig, host, nc, nslookup, ping, traceroute, wget, whois...",
		Files: []string{"network.toml"},
	},
	{
		Label:    "Kubernetes",
		Desc:     "kubectl, docker, helm, kustomize, flux, krew, kubectx, stern, docker-compose",
		Files:    []string{"kubernetes.toml"},
		Builtins: []string{"kubectl", "docker"},
	},
	{
		Label:    "Cloud & CI/CD",
		Desc:     "gcloud, gsutil, pulumi, sops, fly (Concourse), terraform (plan/validate/show)",
		Files:    []string{"concourse.toml", "gsutil.toml", "sops.toml", "terraform.toml"},
		Builtins: []string{"gcloud", "pulumi"},
	},
	{
		Label: "Dev tools",
		Desc:  "make, shellcheck, yamllint",
		Files: []string{"dev-tools.toml"},
	},
	{
		Label:    "Node.js",
		Desc:     "npm, npx, tsc, eslint, prettier",
		Files:    []string{"typescript.toml"},
		Builtins: []string{"npm"},
	},
	{
		Label: "Go",
		Desc:  "go test/build/vet/mod/..., gofmt, goreleaser (check/build)",
		Files: []string{"go.toml"},
	},
	{
		Label: "Rust",
		Desc:  "cargo build/check/test/clippy/..., rustc",
		Files: []string{"rust.toml"},
	},
	{
		Label: "Python",
		Desc:  "uv, ruff, ty",
		Files: []string{"python.toml"},
	},
}

// GenerateConfigs creates selected config files in the given directory.
// If selectedFiles is nil, all DefaultConfigs are generated.
// disabledBuiltins lists built-in tool names to disable in config.toml.
// writableDirs is the list of directories allowed for write operations.
// overwriteGlobal replaces an existing config.toml if true.
// Returns lists of created and skipped files.
func GenerateConfigs(dir string, selectedFiles, disabledBuiltins map[string]bool, writableDirs []string, overwriteGlobal bool) (created, skipped []string, err error) {
	toolsDir := filepath.Join(dir, "tools.d")
	if err := os.MkdirAll(toolsDir, 0755); err != nil {
		return nil, nil, fmt.Errorf("cannot create %s: %w", toolsDir, err)
	}

	for name, content := range DefaultConfigs {
		if selectedFiles != nil && !selectedFiles[name] {
			continue
		}
		path := filepath.Join(toolsDir, name)
		if _, err := os.Stat(path); err == nil {
			skipped = append(skipped, name)
			continue
		}
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return created, skipped, fmt.Errorf("writing %s: %w", path, err)
		}
		created = append(created, name)
	}

	// Write global config.toml
	globalPath := filepath.Join(dir, "config.toml")
	exists := func() bool { _, err := os.Stat(globalPath); return err == nil }
	if exists() && !overwriteGlobal {
		skipped = append(skipped, "config.toml")
	} else {
		content := buildGlobalConfig(writableDirs, disabledBuiltins)
		if err := os.WriteFile(globalPath, []byte(content), 0644); err != nil {
			return created, skipped, fmt.Errorf("writing %s: %w", globalPath, err)
		}
		created = append(created, "config.toml")
	}

	return created, skipped, nil
}

// GenerateDefaults creates all default config files (non-interactive).
func GenerateDefaults(dir string) (created, skipped []string, err error) {
	return GenerateConfigs(dir, nil, nil, []string{"/tmp"}, false)
}

// AllBuiltins returns the sorted list of all builtin names referenced by Categories.
func AllBuiltins() []string {
	seen := make(map[string]bool)
	for _, cat := range Categories {
		for _, b := range cat.Builtins {
			seen[b] = true
		}
	}
	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	slices.Sort(names)
	return names
}

// buildGlobalConfig generates the config.toml content with explicit [builtins] section.
func buildGlobalConfig(writableDirs []string, disabledBuiltins map[string]bool) string {
	var b strings.Builder
	quoted := make([]string, len(writableDirs))
	for i, d := range writableDirs {
		quoted[i] = fmt.Sprintf("%q", d)
	}
	fmt.Fprintf(&b, "writable_dirs = [%s]\n", strings.Join(quoted, ", "))
	b.WriteString(auditConfigBlock())
	b.WriteString("\n[builtins]\n")

	for _, name := range AllBuiltins() {
		if disabledBuiltins[name] {
			fmt.Fprintf(&b, "%s = false\n", name)
		} else {
			fmt.Fprintf(&b, "%s = true\n", name)
		}
	}
	return b.String()
}
